SELECT * FROM POST2 ORDER BY POST_NO DESC;

-- 하나의 쿼리문: REPORT2 데이터 생성
WITH POST_AUTHOR AS (
    SELECT MEMBER_NO 
    FROM POST2 
    WHERE POST_NO = 496
),
RANDOM_COUNT AS (
    SELECT FLOOR(DBMS_RANDOM.VALUE(3,8)) AS report_count 
    FROM DUAL
),
REPORTERS AS (
    SELECT MEMBER_NO 
    FROM (
        SELECT MEMBER_NO
        FROM MEMBER2 M
        WHERE NOT EXISTS (SELECT 1 FROM POST_AUTHOR P WHERE P.MEMBER_NO = M.MEMBER_NO)
        ORDER BY DBMS_RANDOM.VALUE
    )
    WHERE ROWNUM <= (SELECT report_count FROM RANDOM_COUNT)
)
SELECT 
    SEQ_REPORT2_NO.NEXTVAL AS REPORT_NO,
    R.MEMBER_NO AS AUTHOR_NO,
    (SELECT MEMBER_NO FROM POST_AUTHOR) AS REPORTED_NO,
    500 AS POST_NO,
    SYSDATE - ROUND(DBMS_RANDOM.VALUE(0,30)) AS REPORT_DATE,
    '부적절한 게시글입니다_' || R.MEMBER_NO AS REPORT_CONTENT,
    0 AS IS_CHECKED,
    FLOOR(DBMS_RANDOM.VALUE(1,5)) AS REPORTTYPE_NO
FROM REPORTERS R;

COMMIT;