-- 하나의 쿼리문: REPORT2 데이터 생성
INSERT INTO REPORT2 (
    REPORT_NO, AUTHOR_NO, REPORTED_NO, POST_NO,
    REPORT_DATE, REPORT_CONTENT, IS_CHECKED, REPORTTYPE_NO
)
WITH POST_AUTHOR AS (
    SELECT MEMBER_NO 
    FROM POST2 
    WHERE POST_NO =500 -- 여기 함께 수정해야햄!!!!!!!!!!!!!!!!!!!
),
RANDOM_COUNT AS (
    SELECT FLOOR(DBMS_RANDOM.VALUE(3,8)) AS report_count 
    FROM DUAL
),
REPORTERS AS (
    SELECT MEMBER_NO 
    FROM (
        SELECT MEMBER_NO
        FROM MEMBER2 M
        WHERE NOT EXISTS (SELECT 1 FROM POST_AUTHOR P WHERE P.MEMBER_NO = M.MEMBER_NO)
        ORDER BY DBMS_RANDOM.VALUE
    )
    WHERE ROWNUM <= (SELECT report_count FROM RANDOM_COUNT)
)
SELECT 
    SEQ_REPORT2_NO.NEXTVAL,
    R.MEMBER_NO,
    (SELECT MEMBER_NO FROM POST_AUTHOR),
    500,-- 여기 함께 수정해야햄!!!!!!!!!!!!!!!!!!!
    SYSDATE - ROUND(DBMS_RANDOM.VALUE(0,30)),
    '부적절한 게시글입니다_' || R.MEMBER_NO,
    0,
    FLOOR(DBMS_RANDOM.VALUE(1,5))
FROM REPORTERS R;

select * from report2;