DECLARE
BEGIN
	FOR i IN 1..100 LOOP
		INSERT INTO CART2 (
			CART_NO,
			IS_PAYMENT,
			POST_NO,
			PAYMENT_NO,
			MEMBER_NO
		) VALUES (
			SEQ_CART2_NO.NEXTVAL,
			0,
			FLOOR(DBMS_RANDOM.VALUE(1,50)),
			NULL,
			FLOOR(DBMS_RANDOM.VALUE(1,11))
		);
	END LOOP;
	COMMIT;
END;

-- 위의 쿼리문을 2번 처리 실패하면서 CART_NO에 1,2 값이 없어서 아래 로직으로 넣어줌
INSERT INTO CART2 (
			CART_NO,
			IS_PAYMENT,
			POST_NO,
			PAYMENT_NO,
			MEMBER_NO
		) VALUES (
			2,
			0,
			FLOOR(DBMS_RANDOM.VALUE(1,50)),
			NULL,
			FLOOR(DBMS_RANDOM.VALUE(1,11))
		);
	
SELECT * FROM CART2;

ALTER TABLE CART2 MODIFY PAYMENT_NO NULL;